 <sect2 xml:id="S.de_113.68.0">
  <title xml:id="de_113.68.0">DE-113.68.0 Subfield bitmap</title>
  <indexterm>
   <primary>Data Elements</primary>
   <secondary>DE 113.68.0 - Subfield bitmap</secondary>
  </indexterm>
  <simplesect>
   <title>Data Element: 113.68.0</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Format: b64</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Description</title>
   <para> 
    Subfield bitmap (supports up to 64 subfields)
   </para>
  </simplesect>
 </sect2> 

 <sect2 xml:id="S.de_113.68.1">
  <title xml:id="de_113.68">DE-113.68.1 PayFac ID</title>
  <indexterm>
   <primary>Data Elements</primary>
   <secondary>DE 113.68.1 - PayFac ID</secondary>
  </indexterm>
  <simplesect>
   <title>Data Element: 113.68.1</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Format: AN1</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Description</title>
   <para>
    Payment facilitator marketplace id.
   </para>
  </simplesect>
 </sect2> 

 <sect2 xml:id="S.de_113.68.2">
  <title xml:id="de_113.68">DE-113.68.2 PayFac MID</title>
  <indexterm>
   <primary>Data Elements</primary>
   <secondary>DE 113.68.2 - PayFac MID</secondary>
  </indexterm>
  <simplesect>
   <title>Data Element: 113.68.2</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Format: AN15</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Description</title>
   <para>
    Payment facilitator sub merchant ID.
   </para>
  </simplesect>
 </sect2> 

