 <sect2 xml:id="S.de_113.67.0">
  <title xml:id="de_113.67.0">DE-113.67.0 Subfield bitmap</title>
  <indexterm>
   <primary>Data Elements</primary>
   <secondary>DE 113.67.0 - Subfield bitmap</secondary>
  </indexterm>
  <simplesect>
   <title>Data Element: 113.67.0</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Format: b64</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Description</title>
   <para> 
    Subfield bitmap (supports up to 64 subfields)
   </para>
  </simplesect>
 </sect2> 
 <sect2 xml:id="S.de_113.67.1">
  <title xml:id="de_113.67">DE-113.67.1 PAN Source</title>
  <indexterm>
   <primary>Data Elements</primary>
   <secondary>DE 113.67.1 - PAN Source</secondary>
  </indexterm>
  <simplesect>
   <title>Data Element: 113.67.1</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Format: AN1</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Description</title>
   <para> 
     PAN Source
     <itemizedlist>
       <listitem><para><emphasis role="bold">1</emphasis> - Card on File</para></listitem>
       <listitem><para><emphasis role="bold">2</emphasis> - Manual entry</para></listitem>
       <listitem><para><emphasis role="bold">3</emphasis> - Application entry</para></listitem>
     </itemizedlist>
   </para>
  </simplesect>
 </sect2> 
 <sect2 xml:id="S.de_113.67.2">
  <title xml:id="de_113.67.2">DE-113.67.2 Payment Application Instance-ID</title>
  <indexterm>
   <primary>Data Elements</primary>
   <secondary>DE 113.67.2 - Papp-ID</secondary>
  </indexterm>
  <simplesect>
   <title>Data Element: 113.68.2</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Format: AN..255</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Description</title>
   <para> 
     Payment application Instance ID used in pre/post tokenization messages.
   </para>
  </simplesect>
 </sect2> 
 <sect2 xml:id="S.de_113.67.3">
  <title xml:id="de_113.67.3">DE-113.67.3 Active Tokens Count</title>
  <indexterm>
   <primary>Data Elements</primary>
   <secondary>DE 113.67.3 - Active Tokens Count</secondary>
  </indexterm>
  <simplesect>
   <title>Data Element: 113.67.3</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Format: N 2</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Description</title>
   <para> 
     Active tokens count.
   </para>
  </simplesect>
 </sect2> 
 <sect2 xml:id="S.de_113.67.4">
  <title xml:id="de_113.67.4">DE-113.67.4 Wallet Provider Acct Hash</title>
  <indexterm>
   <primary>Data Elements</primary>
   <secondary>DE 113.67.4 - Wallet Provider Acct Hash</secondary>
  </indexterm>
  <simplesect>
   <title>Data Element: 113.67.4</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Format: AN..64</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Description</title>
   <para> 
     Wallet Service Provider Account ID Hash.
   </para>
  </simplesect>
 </sect2> 

 <sect2 xml:id="S.de_113.67.5">
  <title xml:id="de_113.67.5">DE-113.67.5 Tokenization Cardholder Name</title>
  <indexterm>
   <primary>Data Elements</primary>
   <secondary>DE 113.67.5 - Tokenization Cardholder Name</secondary>
  </indexterm>
  <simplesect>
   <title>Data Element: 113.67.5</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Format: AN..64</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Description</title>
   <para> 
     Tokenization Cardholder Name.
   </para>
  </simplesect>
 </sect2> 

 <sect2 xml:id="S.de_113.67.6">
  <title xml:id="de_113.67.6">DE-113.67.6 Token Type</title>
  <indexterm>
   <primary>Data Elements</primary>
   <secondary>DE 113.67.6 - Token Type</secondary>
  </indexterm>
  <simplesect>
   <title>Data Element: 113.67.6</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Format: AN..16</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Description</title>
   <para> 
     Token Type.
   </para>
  </simplesect>
 </sect2> 

 <sect2 xml:id="S.de_113.67.7">
  <title xml:id="de_113.67.7">DE-113.67.7 Consumer language</title>
  <indexterm>
   <primary>Data Elements</primary>
   <secondary>DE 113.67.7 - Consumer language</secondary>
  </indexterm>
  <simplesect>
   <title>Data Element: 113.67.7</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Format: AN 2</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Description</title>
   <para> 
     Consumer language.
   </para>
  </simplesect>
 </sect2> 

 <sect2 xml:id="S.de_113.67.8">
  <title xml:id="de_113.67.8">DE-113.67.8 Device Location</title>
  <indexterm>
   <primary>Data Elements</primary>
   <secondary>DE 113.67.8 - Device Location</secondary>
  </indexterm>
  <simplesect>
   <title>Data Element: 113.67.8</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Format: AN..255</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Description</title>
   <para> 
     Device location information.
   </para>
  </simplesect>
 </sect2> 

 <sect2 xml:id="S.de_113.67.9">
  <title xml:id="de_113.67.9">DE-113.67.9 Device Fingerprint</title>
  <indexterm>
   <primary>Data Elements</primary>
   <secondary>DE 113.67.9 - Device Name</secondary>
  </indexterm>
  <simplesect>
   <title>Data Element: 113.67.9</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Format: AN..999 (JSON/base64)</title>
   <para/>
  </simplesect>
  <simplesect>
   <title>Description</title>
   <para> 
     base64 encoded JSON payload containing device fingerprint data, such
     as device name, source IP, geolocation data, IMEI/mobile number.
   </para>
  </simplesect>
 </sect2> 

